### ISSUE TITLE
importer cpR8x - get users

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1152]
Finally we are just importing access roles as before to the object table. We enhanced the detail level to be able to display information about the access-roles in the future.

**Comment by Robin-Smets** [comment]
So, the api call works. I am pretty much at the same point like in the drafted PR for the TODO: re-add user import. The normalizedConfig has an attribute 'user_objects' now, which is a collection of the users:

![Image](https://github.com/user-attachments/assets/359415bb-3f55-430b-bdcf-7e1727e3d860)

Because of the rest of get_config I assume that these objects have to be in "users". I tried to set them there, but I got an error. I assume, that I have to set them in the nativeConfig as well to have them both consistent, but I am not sure if that is right or if there is some old deprecated logic that is blocking here.

![Image](https://github.com/user-attachments/assets/bac63a4d-5be4-4bab-8a61-46faeef7ae35)

> 2025-03-06T10:29:53+0100 [ERROR] [common.py :get_config: 293]   import_management - unspecified error while getting config: Traceback (most recent call last):
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/common.py", line 274, in get_config_from_api
>     _, configNormalized = fw_module.get_config(configNative, importState)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/checkpointR8x/fwcommon.py", line 328, in get_config
>     normalizedConfig2 = FwConfigNormalized(action=ConfigAction.INSERT,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for FwConfigNormalized
> users
>   value is not a valid dict (type=type_error.dict)
> 
> 2025-03-06T10:29:53+0100 [INFO ] [fwo_base.p:writeAlert: 118] FWORCHAlert - "source": "import", "mgmId": 3, "title": "import error", "description": "  import_management - unspecified error while getting config: Traceback (most recent call last):\n  File \"/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/common.py\", line 274, in get_config_from_api\n    _, configNormalized = fw_module.get_config(configNative, importState)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/checkpointR8x/fwcommon.py\", line 328, in get_config\n    normalizedConfig2 = FwConfigNormalized(action=ConfigAction.INSERT,\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pydantic/main.py\", line 341, in pydantic.main.BaseModel.__init__\npydantic.error_wrappers.ValidationError: 1 validation error for FwConfigNormalized\nusers\n  value is not a valid dict (type=type_error.dict)\n", "alertCode": 14, "severity": 2, "import_id": 108, "mgm_name": "sting-mgmt"
> 2025-03-06T10:29:53+0100 [INFO ] [fwo_api.py:complete_i: 716] import_management: import no. 108 for management sting-mgmt (id=3) threw errors, change_count: 0, duration: 101s, ERRORS:   import_management - unspecified error while getting config: Traceback (most recent call last):
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/common.py", line 274, in get_config_from_api
>     _, configNormalized = fw_module.get_config(configNative, importState)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/checkpointR8x/fwcommon.py", line 328, in get_config
>     normalizedConfig2 = FwConfigNormalized(action=ConfigAction.INSERT,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for FwConfigNormalized
> users
>   value is not a valid dict (type=type_error.dict)
> 
> 2025-03-06T10:29:53+0100 [ERROR] [import-mgm:<module>  :  69] import-mgm - error while importing mgmId=3: Traceback (most recent call last):
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/import-mgm.py", line 54, in <module>
>     error_count = import_management(
>                   ^^^^^^^^^^^^^^^^^^
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/common.py", line 104, in import_management
>     config_changed_since_last_import, configNormalized = get_config_from_api(importState, {})
>                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/common.py", line 274, in get_config_from_api
>     _, configNormalized = fw_module.get_config(configNative, importState)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/robins/Source/FWO_2/firewall-orchestrator/roles/importer/files/importer/checkpointR8x/fwcommon.py", line 328, in get_config
>     normalizedConfig2 = FwConfigNormalized(action=ConfigAction.INSERT,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for FwConfigNormalized
> users
>   value is not a valid dict (type=type_error.dict)

Please tell me how to finalize these issues.

**Comment by tpurschke** [comment]
missing toDict()?
e.g.
```python
    def toDict (self):
        result = {
            'obj_uid': self.obj_uid,
            'obj_name': self.obj_name,
            'obj_color_id': self.obj_color_id,
            'obj_member_refs': self.obj_member_refs,
            'obj_member_names': self.obj_member_names,
            'obj_comment': self.obj_comment,
            'mgm_id': self.mgm_id,
            'obj_create': self.obj_create,
            'obj_last_seen': self.obj_last_seen,
            'obj_typ_id': self.obj_typ_id
        }
```

**Comment by tpurschke** [comment]
buildUserObjUidToIdMapFromApi has not been implemented yet.
there is no rule_user table because the user ref is contained in rule_from and rule_to.

**Comment by Robin-Smets** [comment]
After understanding the import and the database better I looked into this issue again and changed the description that it reflects what I think needs to be done in this issue.

 @tpurschke

**Comment by Robin-Smets** [comment]
No its not completed yet, but there will be a PR today.

**Comment by Robin-Smets** [comment]
Can be closed when #3083 is merged. Ill move the leftovers (check legacy support and display access role details) to parent issue.
