### ISSUE TITLE
UI settings user menu bug

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1178]
when navigating to users under settings, the following bug pops up: "Add user locally - Unclassified error: . See log for details!"
Seems to be a missing permission on hasura API according to ui.log:
```console
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - API Connection (APIConnection.cs in line 84): Error while sending query to GraphQL API. Caught by GraphQL client library.
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message: field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - API Connection (APIConnection.cs in line 106): Error while sending query to GraphQL API.
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  ---
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Exception thrown:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  Exception
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Stack Trace:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName)
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - Add user locally (MainLayout.razor in line 122): Unspecified error occured:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  ---
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Exception thrown:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  Exception
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Stack Trace:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName)
Sep 16 15:09:39 fwodemo fworch-ui[24272]:    at FWO.Ui.Pages.Settings.SettingsUsers.addUserToDb(UiUser user)
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - API Connection (APIConnection.cs in line 84): Error while sending query to GraphQL API. Caught by GraphQL client library.
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message: field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - API Connection (APIConnection.cs in line 106): Error while sending query to GraphQL API.
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  ---
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Exception thrown:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  Exception
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Stack Trace:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName)
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Error - Add user locally (MainLayout.razor in line 122): Unspecified error occured:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  ---
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Exception thrown:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  Exception
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Message:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  field "insert_uiuser" not found in type: 'mutation_root'
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  
Sep 16 15:09:39 fwodemo fworch-ui[24272]: Stack Trace:
Sep 16 15:09:39 fwodemo fworch-ui[24272]:  at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName)
Sep 16 15:09:39 fwodemo fworch-ui[24272]:    at FWO.Ui.Pages.Settings.SettingsUsers.addUserToDb(UiUser user)
```

**Comment by tpurschke** [comment]
could not reproduce it
