### ISSUE TITLE
middleware report scheduler - catch errors

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1298]
- [x] catch the following error. it occuring during scheduled report generation should not result in mw server dying:

```
tim@fworch-comp:~$ sudo systemctl status fworch-middleware.service 
● fworch-middleware.service - FWOrch Middleware Server
     Loaded: loaded (/lib/systemd/system/fworch-middleware.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-11-19 09:56:57 CET; 2h 5min ago
    Process: 11550 ExecStartPre=/bin/sleep 10 (code=exited, status=0/SUCCESS)
    Process: 11557 ExecStart=/usr/local/fworch/middleware/files/FWO.Middleware.Server/bin/Release/net5.0/FWO.Middleware.Server (code=exited, status=0/SUCCESS)
   Main PID: 11557 (code=exited, status=0/SUCCESS)

Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]:  AggregateException
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]: Message:
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]:  One or more errors occurred. (field "language" not found in type: 'query_root'
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]: )
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]: Stack Trace:
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]:  at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]:    at FWO.Config.Api.GlobalConfig..ctor(String jwt) in /usr/local/fworch/lib/files/FWO.Config.Api/GlobalConfig.cs:line 71
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]: info: Microsoft.Hosting.Lifetime[0]
Nov 19 09:56:57 fworch-comp fworch.middleware-server[11557]:       Application is shutting down...
Nov 19 09:56:57 fworch-comp systemd[1]: fworch-middleware.service: Succeeded.
```
--> @NilsPur adds infinite retry instead of hard fail

- [x] 2nd error (unsupported output format)

```
Nov 26 12:01:47 fworch-comp fworch.middleware-server[600635]: Info - Jwt generation (JwtWriter.cs in line 87): Generated JWT eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1pZGRsZXdhcmUtc2VydmVyIiwieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJtaWRkbGV3YXJlLXNlcnZlciJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJtaWRkbGV3YXJlLXNlcnZlciIsIm5iZiI6MTYzNzkyNDQ0NywiZXhwIjo3OTQ5MjcxNzA3LCJpYXQiOjE2Mzc5MjQ0NDcsImlzcyI6IkZXTyBNaWRkbGV3YXJlIE1vZHVsZSIsImF1ZCI6IkZXTyJ9.KsLQIgrigxQzOvRjnC76Fn1ZuukVZ4XJY7vNBYtGJfW2l6QTjbUs8_bshsenMw5eh--vCm3dOts_i6xrGgJAnLzkKBnPLq2FYOzESfxjuUJ5EPFvvN-6rKS3mPz3gruZ7B5v5X1yJuiDqn_XYRnRX9OfF7MLLs6oJglyFI5J4M2ru5EC7YHcvD43LhROIZH48b1vXEGtHLuPos13s5JkEcYpFDkgoOGDrYoC9eLQXOduEI1mmOwZHYvaGGlN7uMoUcJP6D--6kXZQTTb58OaS7lK6TdxIflrZE6ZmyjuBJZepbJn3T2R3z4T_zkhQ79ZFRe0np-nTf9tGHMJ1ORaKA for middleware-server
Nov 26 12:01:47 fworch-comp fworch.middleware-server[600635]: Info - Jwt generation (JwtWriter.cs in line 57): Generated JWT eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJlcHNjaGVkIiwieC1oYXN1cmEtdXNlci1pZCI6IjciLCJ4LWhhc3VyYS11dWlkIjoidWlkPXJlcHNjaGVkLG91PXRlbmFudDAsb3U9b3BlcmF0b3Isb3U9dXNlcixkYz1md29yY2gsZGM9aW50ZXJuYWwiLCJ4LWhhc3VyYS10ZW5hbnQtaWQiOiIxIiwieC1oYXN1cmEtdmlzaWJsZS1tYW5hZ2VtZW50cyI6InsgMTUsNiwxMiwyLDExLDEsNSB9IiwieC1oYXN1cmEtdmlzaWJsZS1kZXZpY2VzIjoieyAxLDIsNSw2LDExLDEyLDE1IH0iLCJyb2xlIjoicmVwb3J0ZXItdmlld2FsbCIsIngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsicmVwb3J0ZXItdmlld2FsbCJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJyZXBvcnRlci12aWV3YWxsIiwibmJmIjoxNjM3OTI0NDQ3LCJleHAiOjE2Mzc5Mzg5MDcsImlhdCI6MTYzNzkyNDQ0NywiaXNzIjoiRldPIE1pZGRsZXdhcmUgTW9kdWxlIiwiYXVkIjoiRldPIn0.K8nQq6lBrN0IJ9orlrC3GLZYoawCr03Exyg_2QQFdvoXQTC8YZGJ1lgrO8h3ks3PgmvEQSlvMBZZX10TznIXSP_xMnhqIIJdKZthhGYku_ii2TbR00wjRzpD1SXLeAFroBS4HVATjfLsBD1D5iteKVGSmHZ9Ts__HH0p2pzDZsF4GM7zcOktnqyuQVAJ9o5soGu20rMH0q3wRXpdCGk_ki7ewdCKAQTSQWTJiXZ8Au9s-i5HxXRzrlVCrAvjUaNouSlusPDPacguhwdahRVyLMPVdNxBBSyk5hGK_P6kyrxw9ZaTBtjBO2vSyxnY4ZZS2ccDDW2y4FhGNTlfv5Mrgg for User repsched
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]: Error - Report Scheduling (ReportScheduler.cs in line 190): Generating scheduled report "test-report-api-repsched1201" lead to exception.
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]:  ---
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]: Exception thrown:
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]:  NotSupportedException
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]: Message:
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]:  Output format is not supported.
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]: Stack Trace:
Nov 26 12:02:03 fworch-comp fworch.middleware-server[600635]:  at FWO.Middleware.Server.ReportScheduler.<>c__DisplayClass14_0.<<GenerateReport>b__0>d.MoveNext() in /usr/local/fworch/middleware/files/FWO.Middleware.Server/ReportScheduler.cs:line 167
Nov 26 12:07:47 fworch-comp fworch.middleware-server[600635]: Info - Jwt generation (JwtWriter.cs in line 87): Generated JWT eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1pZGRsZXdhcmUtc2VydmVyI
```
@abarz722 graying out CSV (coming soon) in interactive & scheduled reporting

- [x]  just switching between main menu entries (report/schedule/archive):+

```console
Uncaught (in promise) Error: Blazor has already started.
    at Object.Gn [as start] (blazor.server.js:1)
    at VM8:31
blazor.server.js:1 [2021-11-29T13:13:35.601Z] Information: Normalizing '_blazor' to 'https://localhost:10443/_blazor'.
blazor.server.js:1 [2021-11-29T13:13:35.693Z] Information: WebSocket connected to wss://localhost:10443/_blazor?id=ZHdlA5V0Q-HXikh4mwDmCw.
blazor.server.js:1 [2021-11-29T13:14:17.810Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
log @ blazor.server.js:1
blazor.server.js:1 [2021-11-29T13:14:17.811Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at _t.send (blazor.server.js:1)
    at Tt._sendMessage (blazor.server.js:1)
    at Tt._sendWithProtocol (blazor.server.js:1)
    at Tt.send (blazor.server.js:1)
    at blazor.server.js:1
    at _e (blazor.server.js:1)
    at be (blazor.server.js:1)
    at blazor.server.js:1
    at blazor.server.js:1
    at Array.forEach (<anonymous>)
```

**Comment by tpurschke** [comment]
@abarz722 - could you tackle this?

**Comment by tpurschke** [comment]
fixed
