### ISSUE TITLE
reporting - json doc size issue

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1312]
need to handle this somehow, 
 -  do we need to split up reports into chunks?
 - can we raise the limit? where?

see (dotnet/runtime#30746),

error:
```
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Exception thrown:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  ArgumentException
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Message:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  The JSON value of length 260033126 is too large and not supported.
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Stack Trace:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueTooLarge(Int32 tokenLength)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Utf8JsonWriter.WriteStringValue(ReadOnlySpan`1 value)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.StringConverter.Write(Utf8JsonWriter writer, String value, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpRequest.ToHttpRequestMessage(GraphQLHttpClientOptions options, IGraphQLJsonSerializer serializer)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs:line 75
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Error - Report Scheduling (ReportScheduler.cs in line 196): Generating scheduled report "test-report-api-repsched1211" lead to exception.
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  ---
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Exception thrown:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  ArgumentException
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Message:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  The JSON value of length 260033126 is too large and not supported.
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]: Stack Trace:
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:  at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueTooLarge(Int32 tokenLength)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Utf8JsonWriter.WriteStringValue(ReadOnlySpan`1 value)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.StringConverter.Write(Utf8JsonWriter writer, String value, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue& value, Type type, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Serializer.SystemTextJson.ImmutableConverter.Write(Utf8JsonWriter writer, Object value, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`3.OnTryWrite(Utf8JsonWriter writer, TCollection dictionary, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Serializer.SystemTextJson.SystemTextJsonSerializer.SerializeToString(GraphQLRequest request)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpRequest.ToHttpRequestMessage(GraphQLHttpClientOptions options, IGraphQLJsonSerializer serializer)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs:line 75
Nov 19 12:13:19 fworch-comp fworch.middleware-server[21618]:    at FWO.Middleware.Server.ReportScheduler.<>c__DisplayClass14_0.<<GenerateReport>b__0>d.MoveNext() in /usr/local/fworch/middleware/files/FWO.Middleware.Server/ReportScheduler.cs:line 192


```

**Comment by tpurschke** [comment]
```
orch.middleware-server[152708]:       35601,
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:       35602,
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:       35603,
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:       35604,
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:       35611,
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Info - User Validation (Ldap.cs in line 91): Validating User: "admin" ...

==> /var/log/fworch/ldap.log <==
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 fd=11 ACCEPT from IP=127.0.0.1:54346 (IP=0.0.0.0:636)
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 fd=11 TLS established tls_ssf=256 ssf=256
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=0 BIND dn="uid=inspector,ou=systemuser,ou=user,dc=fworch,dc=internal" method=128
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=0 BIND dn="uid=inspector,ou=systemuser,ou=user,dc=fworch,dc=internal" mech=SIMPLE ssf=0
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=0 RESULT tag=97 err=0 text=
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=1 SRCH base="ou=operator,ou=user,dc=fworch,dc=internal" scope=2 deref=0 filter="(&(|(?objectClass=user)(objectClass=person)(objectClass=inetOrgPerson)(objectClass=organizationalPerson))(|(cn=admin)(uid=admin)))"
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=1 SRCH attr=* memberof
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=2 BIND anonymous mech=implicit ssf=0
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=2 BIND dn="uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal" method=128
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=2 BIND dn="uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal" mech=SIMPLE ssf=0
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=2 RESULT tag=97 err=0 text=
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 op=3 UNBIND

==> /var/log/fworch/middleware.log <==
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Info - User Authentication (AuthenticationTokenController.cs in line 131): User successfully validated as FWO.Api.Data.UiUser with DN uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal

==> /var/log/fworch/ldap.log <==
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11501 fd=11 closed
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 fd=11 ACCEPT from IP=127.0.0.1:54348 (IP=0.0.0.0:636)
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 fd=11 TLS established tls_ssf=256 ssf=256
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=0 BIND dn="uid=inspector,ou=systemuser,ou=user,dc=fworch,dc=internal" method=128
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=0 BIND dn="uid=inspector,ou=systemuser,ou=user,dc=fworch,dc=internal" mech=SIMPLE ssf=0
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=0 RESULT tag=97 err=0 text=
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=1 SRCH base="ou=role,dc=fworch,dc=internal" scope=2 deref=0 filter="(&(objectClass=groupOfUniqueNames)(cn=*))"
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=1 SEARCH RESULT tag=101 err=0 nentries=12 text=
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 op=2 UNBIND
Dec 23 14:08:59 devsrv2 slapd[523]: conn=11502 fd=11 closed

==> /var/log/fworch/middleware.log <==
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Error - API Connection (APIConnection.cs in line 125): Error while sending query to GraphQL API. Query: query getTenantId($tenant_name: String!) {
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:   tenant(where: { tenant_name: { _eq: $tenant_name } }) {
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:     tenant_id
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:   }
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: }, variables: { tenant_name = user }
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:  GraphQLHttpRequestException
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:  The HTTP request failed with status code ServiceUnavailable
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:  at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
Dec 23 14:08:59 devsrv2 fworch.middleware-server[152708]:    at FWO.ApiClient.APIConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs:line 81
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Error - Subscription (Program.cs in line 46): Subscription lead to exception.
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: --- End of stack trace from previous location ---
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Error - Report scheduler (ReportScheduler.cs in line 63): Api subscription lead to exception. Retry subscription.
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:07 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Error - Subscription (Program.cs in line 46): Subscription lead to exception.
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Error - Report scheduler (ReportScheduler.cs in line 63): Api subscription lead to exception. Retry subscription.
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:16 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Error - Subscription (Program.cs in line 46): Subscription lead to exception.
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: --- End of stack trace from previous location ---
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Error - Report scheduler (ReportScheduler.cs in line 63): Api subscription lead to exception. Retry subscription.
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]: --- End of stack trace from previous location ---
Dec 23 14:09:24 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Error - Subscription (Program.cs in line 46): Subscription lead to exception.
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Error - Report scheduler (ReportScheduler.cs in line 63): Api subscription lead to exception. Retry subscription.
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  The server returned status code '503' when status code '101' was expected.
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]: Stack Trace:
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:  at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token)
Dec 23 14:09:31 devsrv2 fworch.middleware-server[152708]:    at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d.MoveNext()
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]: Error - Subscription (Program.cs in line 46): Subscription lead to exception.
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]:  ---
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]: Exception thrown:
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]:  WebSocketException
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]: Message:
Dec 23 14:09:40 devsrv2 fworch.middleware-server[152708]:  The serve
```
