### ISSUE TITLE
report scheduler - various issues

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1320]
- [x] scheduled html-Report does not contain any objects, just rules  (while interactively exported report is complete with objects)
- [x] firefox only? seconds should be removed (also causes no match if seconds <> 0)
- [x] reports do not get (reliably) scheduled - see error (@abarz722 - tenant-related)
```
==> /var/log/fworch/middleware.log <==
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]: Error - Report Scheduling (ReportScheduler.cs in line 188): Generating scheduled report "current-rules-fi3" lead to exception.
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]:  ---
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]: Exception thrown:
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]:  IndexOutOfRangeException
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]: Message:
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]:  Index was outside the bounds of the array.
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]: Stack Trace:
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]:  at FWO.Middleware.Controllers.AuthManager.GetTenantAsync(UiUser user)
Dec  6 17:37:52 orctstfits202 fworch.middleware-server[376161]:    at FWO.Middleware.Server.ReportScheduler.<>c__DisplayClass14_0.<<GenerateReport>b__0>d.MoveNext() in /usr/local/fworch/middleware/files/FWO.Middleware.Server/ReportScheduler.cs:line 133
```

**Comment by tpurschke** [comment]
all fixed (by reverting wkhtmlpdf
