### ISSUE TITLE
report pdf generation broken with HakanL/WkHtmlToPdf-DotNet >1.5.59

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1341]
got the following error under ubuntu 20.04 with dotnet 6
`One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.) `

dependency: https://github.com/HakanL/WkHtmlToPdf-DotNet

error log
```
==> /var/log/fworch/ui.log <==
Dec  6 18:01:38 fworch-comp fworch-ui[244223]: Message:
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:  One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
Dec  6 18:01:38 fworch-comp fworch-ui[244223]: Stack Trace:
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at System.Threading.Tasks.Task.Wait()
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at WkHtmlToPdfDotNet.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at WkHtmlToPdfDotNet.SynchronizedConverter.Convert(IDocument document)
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at FWO.Report.ReportBase.ToPdf() in /usr/local/fworch/lib/files/FWO.Report/ReportBase.cs:line 131
Dec  6 18:01:38 fworch-comp fworch-ui[244223]:    at FWO.Ui.Pages.Reporting.ReportExport.<Export>b__17_0() in /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/ReportExport.razor:line 133

```

Libraries installed:
```
tim@fworch-comp:~/tpurschke-fwo$ dpkg -l | grep jpeg
ii  libjpeg-turbo8:amd64                       2.0.3-0ubuntu1.20.04.1                amd64        IJG JPEG compliant runtime library.
ii  libjpeg-turbo8-dev:amd64                   2.0.3-0ubuntu1.20.04.1                amd64        Development files for the IJG JPEG library
ii  libjpeg62:amd64                            1:6b2-3                               amd64        Independent JPEG Group's JPEG runtime library (version 6.2)
ii  libjpeg8:amd64                             8c-2ubuntu8                           amd64        Independent JPEG Group's JPEG runtime library (dependency package)
ii  libjpeg8-dev:amd64                         8c-2ubuntu8                           amd64        Independent JPEG Group's JPEG runtime library (dependency package)
tim@fworch-comp:~/tpurschke-fwo$ 
```

**Comment by tpurschke** [comment]
reverting to pdf lib 1.5.59 restored functionality

**Comment by tpurschke** [comment]
now I cannot get PDFs generated with v1.5.59.
tested on deb10, ubu20.04

**Comment by tpurschke** [comment]
created https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/72
