### ISSUE TITLE
big rulebases (>40k rules) cause import to fail

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1441]
currently encountered with FortiManager import
test data on xfer-server (mgm_id_56_config_native.json.anon.gz)

hasura api server crashes:
```
tim@debian11:~/firewall-orchestrator-tpur$ sudo docker ps --all
CONTAINER ID   IMAGE                          COMMAND                  CREATED        STATUS                       PORTS     NAMES
5443eff06540   hasura/graphql-engine:v2.1.1   "graphql-engine serve"   23 hours ago   Exited (137) 3 minutes ago             fworch-api
tim@debian11:~/firewall-orchestrator-tpur$ 

```
python error:
```
         "rule_src_neg": false,
          "rule_dst_neg": false,
          "rule_svc_neg": false,
          "rule_src_refs": "b398bc60-1508-51eb-f648-9197a6358126|b398d088-1508-51eb-f767-2459940e70b5|b398e42e-1508-51eb-bfb6-88f4c1467010|b398fad6-1508-51eb-e598-e93dac3cff02|b3991386-1508-51eb-0e6a-e81237bc7d01|b3992948-1508-51eb-b38c-ff1643bea52a",
          "rule_dst_refs": "d11e83e8-722a-51ec-2a91-0abfa116bef6|fdd91a9c-722a-51ec-4daf-23e42fd908be",
          "rule_svc_refs": "TCP_03389_rdp"
        }
      ]
    }
  },
  "query": "\n        mutation import($importId: bigint!, $mgmId: Int!, $config: jsonb!) {\n            insert_import_config(objects: {import_id: $importId, mgm_id: $mgmId, config: $config}) {\n                affected_rows\n            }\n        }\n    "
}
 and  headers: 
{
  "Content-Type": "application/json",
  "Authorization": "Bearer xxx",
  "x-hasura-role": "importer"
}
Traceback (most recent call last):
  File "/home/tim/dev/tpurschke-fwo/roles/importer/files/importer/fwo_api.py", line 30, in call
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://127.0.0.1:9443/api/v1/graphql
2022-01-14 12:19:57,276 - ERROR - fwo_api: failed to write importable config for mgm id 21
Traceback (most recent call last):
  File "/home/tim/dev/tpurschke-fwo/roles/importer/files/importer/fwo_api.py", line 274, in import_json_config
    import_result = call(fwo_api_base_url, jwt, import_mutation,
  File "/home/tim/dev/tpurschke-fwo/roles/importer/files/importer/fwo_api.py", line 34, in call
    raise SystemExit(e) from None
SystemExit: 502 Server Error: Proxy Error for url: https://127.0.0.1:9443/api/v1/graphql
```

**Comment by tpurschke** [comment]
might try to switch type from jsonb to json (see https://stackoverflow.com/questions/12632871/size-limit-of-json-data-type-in-postgresql)
