### ISSUE TITLE
Test - CodeQL Test for C# fails

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1467]
@NilsPur can you have a look at how to get the test running?

https://github.com/CactuseSecurity/firewall-orchestrator/runs/4876536690?check_suite_focus=true

```
  "/home/runner/work/firewall-orchestrator/firewall-orchestrator/roles/FWO.sln" (rebuild target) (1) ->
  "/home/runner/work/firewall-orchestrator/firewall-orchestrator/roles/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj" (Rebuild target) (13) ->
    /usr/share/dotnet/sdk/3.1.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1005: Assets file '/home/runner/work/firewall-orchestrator/firewall-orchestrator/roles/lib/files/FWO.DeviceAutoDiscovery/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v6.0'. Ensure that restore has run and that you have included 'net60' in the TargetFrameworks for your project. [/home/runner/work/firewall-orchestrator/firewall-orchestrator/roles/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
  
      0 Warning(s)
      12 Error(s)
  
  Time Elapsed 00:00:02.01
  Exit code 1
  Attempting to locate build script
  Error: Could not auto-detect a suitable build method
  Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20211208/x64/codeql/csharp/tools/autobuild.sh with arguments .
  
        Exit code 1 and error was:
  
        Error: Could not auto-detect a suitable build method
  
  CommandInvocationError: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20211208/x64/codeql/csharp/tools/autobuild.sh with arguments .
  
        Exit code 1 and error was:
        Error: Could not auto-detect a suitable build method
      at runTool (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:731:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.runAutobuild (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:466:13)
      at async runAutobuild (/home/runner/work/_actions/github/codeql-action/v1/lib/autobuild.js:29:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/autobuild-action.js:57:13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/autobuild-action.js:70:9)
```

**Comment by NilsPur** [comment]
fixed itself
