### ISSUE TITLE
Bugs with latest develop commit 1b6bfc8

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1482]
- [x] Forti-Importer: only a single gw per mgm is imported
- [x] vip nat - when two nat ip addresses are identical, we need to avoid generating more than one object
- [x] fwddos21_root missing xlate dst nat objects - went away
- [x] do we have a query issue when reporting on a management that is currently being imported (need to check that stop_time is set)
- [x] #1497
- [x] 30k ruleset still does not get imported - api sometimes crashes (but no clues in api.log)
- [x] fix rule refs in 30k rule management (see #1509 as prerequisite)
finally running import:

```
2022-02-03 12:32:02,607 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
2022-02-03 12:32:02,702 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 200 None
2022-02-03 12:32:02,704 - INFO - import_management: import no. 386 for management forti-30k (id=6) successful, change_count: 83961, duration: 4761s
```

minor issues
- [x] checkpoint auto-discover.py missing common module

**Comment by tpurschke** [comment]
looks like a timeout of 15 minutes (900 s) but no timeout error visible, setting timeout expl. to 1h now
```console
2022-01-28 08:05:49,805 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
2022-01-28 08:20:49,921 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 502 418
2022-01-28 08:20:49,963 - ERROR - error while sending api_call to url https://127.0.0.1:9443/api/v1/graphql with payload 
{'query': '\n        mutation import($importId: bigint!, $mgmId: Int!, $config: jsonb!, $start_import_flag: Boolean!) {\n            insert_import_config(objects: {start_import_flag: $start_import_flag, import_id: $importId, mgm_id: $mgmId, config: $config}) {\n                affected_rows\n            }\n        }\n    ', 'variables': {'start_import_flag': True, 'importId': 27809, 'mgmId': '45', 'config': {'network_objects': [{'obj_name': 'AnonAACW_10.0.68.145-3', 'obj_typ': 'group', 'obj_memb
 ... [snip] ... 
       "control_id": 27809
        },
        {
          "control_id": 27809,
          "obj_name": "Original",
          "obj_typ": "network",
          "obj_ip": "0.0.0.0/0",
          "obj_uid": "Original",
          "obj_color": "black",
          "obj_comment": "\"original\" network object created by FWO importer for NAT purposes",
          "obj_zone": "global"
        }
      ],
      "service_objects": [],
      "user_objects": [],
      "zone_objects": [],
      "rules": []
    }
  }
} (total query size=285099 bytes)
 and  headers: 
{
  "Content-Type": "application/json",
  "Authorization": "Bearer eyJh[snip]Pw",
  "x-hasura-role": "importer"
}:
Traceback (most recent call last):
  File "/home/tim/dev/firewall-orchestrator/roles/importer/files/importer/fwo_api.py", line 39, in call
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://127.0.0.1:9443/api/v1/graphql

2022-01-28 08:20:49,963 - ERROR - fwo_api: failed to write importable config for mgm id 45
Traceback (most recent call last):
  File "/home/tim/dev/firewall-orchestrator/roles/importer/files/importer/fwo_api.py", line 257, in import_json_config
    import_result = call(fwo_api_base_url, jwt, import_mutation,
  File "/home/tim/dev/firewall-orchestrator/roles/importer/files/importer/fwo_api.py", line 39, in call
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://127.0.0.1:9443/api/v1/graphql
2022-01-28 08:20:49,967 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
2022-01-28 08:20:49,982 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 200 None
2022-01-28 08:20:49,987 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
2022-01-28 08:20:50,070 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 200 None
2022-01-28 08:20:51,258 - DEBUG - full_config size: 77229547 bytes, config2import size: 46830956 bytes
2022-01-28 08:20:51,261 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
2022-01-28 08:20:51,326 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 200 None
2022-01-28 08:20:51,335 - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:9443
```

**Comment by tpurschke** [comment]
and it indeed was a simple apache rev-proxy timeout of 900 s - increased to 3600 s now

**Comment by tpurschke** [comment]
finally the api import works, now running into rule ref issues:
```
2022-01-28 11:01:32,575 - INFO - import_management: import no. 27815 for management Forti dummy (id=45) threw errors, change_count: 0, duration: 3444s
   ERRORS: [{'import_errors': 'ERR-ImpMain@ImpGlobRef;ERR-ImpGlobRef@import_rule_refhandler_main of device 30k-rules (Management: 45)'}]
```

**Comment by tpurschke** [comment]
finally got useful debug output:

```
2022-02-02 11:58:31,691 - DEBUG - https://127.0.0.1:9443 "POST /api/v1/graphql HTTP/1.1" 200 None
2022-02-02 11:58:31,692 - INFO - import_management: import no. 9490 for management 30kmgm (id=4) threw errors, change_count: 29330, duration: 3376s
   ERRORS: [{'import_errors': 'ERR-import_rule_refhandler@rule_uid: be6fd1f0-150d-51eb-7ca2-09a435de0e90\\nERR-import_rule_refhandler@rule_uid: be764eea-150d-51eb-d5dd-c6a6cdd3e831\\nERR-import_rule_refhandler@rule_uid: c9393504-150d-51eb-5b8e-dc725e57c295\\nERR-import_rule_refhandler@rule_uid: f5c822e2-150d-51eb-73f5-a3d5e72ed6dc\\nERR-import_rule_refhandler@rule_uid: 713d3c5a-150e-51eb-5e0e-9420b6291e2b\\nERR-import_rule_refhandler@rule_uid: 719dc61a-150e-51eb-c25a-8805fcf469ef\\nERR-import_rule_refhandler@rule_uid: 71a43338-150e-51eb-a38d-22028fe559f0'}]
   
```

**Comment by tpurschke** [comment]
finis
