### ISSUE TITLE
tests - csharp KeyImporter.cs in line 71 Error while trying to read key from file

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1722]
```
TASK [test : show test results] ************************************************
ok: [fworch-srv] => 
  csharp_tests:
    changed: true
    cmd:
    - dotnet
    - test
    delta: '0:00:07.328715'
    end: '2022-06-01 19:13:51.265105'
    failed: false
    rc: 0
    start: '2022-06-01 19:13:43.936390'
    stderr: ''
    stderr_lines: []
    stdout: |2-
        Determining projects to restore...
        All projects are up-to-date for restore.
        FWO.Logging -> /usr/local/fworch/lib/files/FWO.Logging/bin/Debug/net6.0/FWO.Logging.dll
        FWO.Config.File -> /usr/local/fworch/lib/files/FWO.Config.File/bin/Debug/net6.0/FWO.Config.File.dll
        FWO.Middleware -> /usr/local/fworch/lib/files/FWO.Middleware/bin/Debug/net6.0/FWO.Middleware.dll
      /usr/local/fworch/lib/files/FWO.Api.Client/ApiSubscription.cs(31,21): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
      /usr/local/fworch/lib/files/FWO.Api.Client/GraphQlApiConnection.cs(103,25): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
        FWO.Api.Client -> /usr/local/fworch/lib/files/FWO.Api.Client/bin/Debug/net6.0/FWO.Api.Client.dll
        FWO.Middleware.Client -> /usr/local/fworch/lib/files/FWO.Middleware.Client/bin/Debug/net6.0/FWO.Middleware.Client.dll
      /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(32,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(32,19): warning CS8618: Non-nullable property 'RawConfigItems' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(34,19): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      /usr/local/fworch/lib/files/FWO.Config.Api/Config.cs(34,19): warning CS8618: Non-nullable property 'RawConfigItems' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
      /usr/local/fworch/lib/files/FWO.Config.Api/UserConfig.cs(86,34): warning CS8625: Cannot convert null literal to non-nullable reference type. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
        FWO.Config.Api -> /usr/local/fworch/lib/files/FWO.Config.Api/bin/Debug/net6.0/FWO.Config.Api.dll
      /usr/local/fworch/lib/files/FWO.Report.Filter/Ast/AstNodeFilterDateTimeRange.cs(11,23): warning CS8618: Non-nullable field 'semanticValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj]
        FWO.Report.Filter -> /usr/local/fworch/lib/files/FWO.Report.Filter/bin/Debug/net6.0/FWO.Report.Filter.dll
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(204,29): warning CS8618: Non-nullable property 'DomainList' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(63,57): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(96,67): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(142,82): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs(143,25): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(97,38): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(117,47): warning CS8602: Dereference of a possibly null reference. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
        FWO.DeviceAutoDiscovery -> /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/bin/Debug/net6.0/FWO.DeviceAutoDiscovery.dll
      /usr/local/fworch/test/csharp/FWO.Test/ApiConfigTest.cs(30,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
      /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(19,16): warning CS8618: Non-nullable field 'apiConnection' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
      /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(51,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
      /usr/local/fworch/test/csharp/FWO.Test/ApiTest.cs(17,23): warning CS0169: The field 'ApiTest.apiConnection' is never used [/usr/local/fworch/test/csharp/FWO.Test/FWO.Test.csproj]
        FWO.Test -> /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll
      Test run for /usr/local/fworch/test/csharp/FWO.Test/bin/Debug/net6.0/FWO.Test.dll (.NETCoreApp,Version=v6.0)
      Microsoft (R) Test Execution Command Line Tool Version 17.2.0 (x64)
      Copyright (c) Microsoft Corporation.  All rights reserved.
  
      Starting test execution, please wait...
      A total of 1 test files matched the specified pattern.
      2022-06-01T19:13:50+02:00 Debug - Key extraction (KeyImporter.cs in line 74), Key was succesfully extracted.
      2022-06-01T19:13:50+02:00 Debug - Key extraction (KeyImporter.cs in line 74), Key was succesfully extracted.
      2022-06-01T19:13:50+02:00 Error - Key extraction (KeyImporter.cs in line 71), Error while trying to read key from file.
       ---
      Exception thrown:
       ArgumentOutOfRangeException
      Message:
       Non-negative number required. (Parameter 'count')
      Stack Trace:
       at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
         at FWO.Config.File.KeyImporter.ExtractKeyFromPemAsString(String rawKey) in /usr/local/fworch/lib/files/FWO.Config.File/KeyImporter.cs:line 67
      2022-06-01T19:13:50+02:00 Debug - Key extraction (KeyImporter.cs in line 74), Key was succesfully extracted.
      2022-06-01T19:13:50+02:00 Error - Extract Key (KeyImporter.cs in line 48), unexpected error while trying to extract rsakey from PEM formatted key .
       ---

```

**Comment by NilsPur** [comment]
This is intended - the tests also validate the cases of invalid / missing keys.
Therefore, an exception should be thrown.
