### ISSUE TITLE
UI - issues with userconfig

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1853]
- [ ] JWT refresh leads to "Username must not be empty" error
- [x] @Y4nnikH :  When logging out as some user and logging in as admin next, the before logged in username will be displayed in the nav bar.
- [x] no username displayed in horizontal main nav bar (admin user);  after clicking  "settings - users - sync to ldap" the issue goes away
- [ ] logout/login sometimes fails on first try: the re-login (same user or other user) sometimes fails with error `Maybe backend (API or database) is unreachable. Please contact administrator`

  - might be related to new roles changes in request module (because user admin with admin role) has a problem here
  - might best be reproduced by creating a new user (e.g. auditor) and logging in with this user afterwards
  - a reload fixes it (leads to login)

```
2022-10-12T08:00:01.879068+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-12T08:00:01+02:00 Error - API Connection (GraphQlApiConnection.cs in line 103), Error while sending query to GraphQL API. Caught by GraphQL client library.
2022-10-12T08:00:01.879159+02:00 fwo-ubu22-desktop fworch-ui:  Message: Your requested role is not in allowed roles
2022-10-12T08:00:01.879709+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-12T08:00:01+02:00 Error - API Connection (GraphQlApiConnection.cs in line 138), Error while sending query to GraphQL API. Query: query getUserByDn($dn: String!) {
2022-10-12T08:00:01.879753+02:00 fwo-ubu22-desktop fworch-ui:    uiuser(where: {uuid: {_eq:  $dn } }) {
2022-10-12T08:00:01.879775+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_id
2022-10-12T08:00:01.879793+02:00 fwo-ubu22-desktop fworch-ui:      uuid
2022-10-12T08:00:01.879811+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_username
2022-10-12T08:00:01.879930+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_language
2022-10-12T08:00:01.879968+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_password_must_be_changed
2022-10-12T08:00:01.879987+02:00 fwo-ubu22-desktop fworch-ui:    }
2022-10-12T08:00:01.880005+02:00 fwo-ubu22-desktop fworch-ui:  }
2022-10-12T08:00:01.880023+02:00 fwo-ubu22-desktop fworch-ui:  , variables: {"dn":"uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal"}
2022-10-12T08:00:01.880041+02:00 fwo-ubu22-desktop fworch-ui:   ---
2022-10-12T08:00:01.880058+02:00 fwo-ubu22-desktop fworch-ui:  Exception thrown:
2022-10-12T08:00:01.880076+02:00 fwo-ubu22-desktop fworch-ui:   Exception
2022-10-12T08:00:01.880097+02:00 fwo-ubu22-desktop fworch-ui:  Message:
2022-10-12T08:00:01.880115+02:00 fwo-ubu22-desktop fworch-ui:   Your requested role is not in allowed roles
2022-10-12T08:00:01.880137+02:00 fwo-ubu22-desktop fworch-ui:   
2022-10-12T08:00:01.880155+02:00 fwo-ubu22-desktop fworch-ui:  Stack Trace:
2022-10-12T08:00:01.880300+02:00 fwo-ubu22-desktop fworch-ui:   at FWO.Api.Client.GraphQlApiConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/GraphQlApiConnection.cs:line 107
```

second sample log for requester1 which has roles requester and approver:
```
2022-10-12T14:49:59.591889+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-12T14:49:59+02:00 Audit - AuthenticateUser (AuthStateProvider.cs in line 69), user requester1 successfully authenticated
2022-10-12T14:49:59.695951+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-12T14:49:59+02:00 Error - API Connection (GraphQlApiConnection.cs in line 103), Error while sending query to GraphQL API. Caught by GraphQL client library.
2022-10-12T14:49:59.696070+02:00 fwo-ubu22-desktop fworch-ui:  Message: Your requested role is not in allowed roles
2022-10-12T14:49:59.714098+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-12T14:49:59+02:00 Error - API Connection (GraphQlApiConnection.cs in line 138), Error while sending query to GraphQL API. Query: query getUserByDn($dn: String!) {
2022-10-12T14:49:59.714236+02:00 fwo-ubu22-desktop fworch-ui:    uiuser(where: {uuid: {_eq:  $dn } }) {
2022-10-12T14:49:59.714307+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_id
2022-10-12T14:49:59.714371+02:00 fwo-ubu22-desktop fworch-ui:      uuid
2022-10-12T14:49:59.714457+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_username
2022-10-12T14:49:59.714540+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_language
2022-10-12T14:49:59.714589+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_password_must_be_changed
2022-10-12T14:49:59.714627+02:00 fwo-ubu22-desktop fworch-ui:    }
2022-10-12T14:49:59.714662+02:00 fwo-ubu22-desktop fworch-ui:  }
2022-10-12T14:49:59.714696+02:00 fwo-ubu22-desktop fworch-ui:  , variables: {"dn":"uid=requester1,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal"}
2022-10-12T14:49:59.714731+02:00 fwo-ubu22-desktop fworch-ui:   ---
2022-10-12T14:49:59.714785+02:00 fwo-ubu22-desktop fworch-ui:  Exception thrown:
2022-10-12T14:49:59.714826+02:00 fwo-ubu22-desktop fworch-ui:   Exception
2022-10-12T14:49:59.714855+02:00 fwo-ubu22-desktop fworch-ui:  Message:
2022-10-12T14:49:59.714884+02:00 fwo-ubu22-desktop fworch-ui:   Your requested role is not in allowed roles
2022-10-12T14:49:59.714923+02:00 fwo-ubu22-desktop fworch-ui:   
2022-10-12T14:49:59.714986+02:00 fwo-ubu22-desktop fworch-ui:  Stack Trace:
2022-10-12T14:49:59.715039+02:00 fwo-ubu22-desktop fworch-ui:   at FWO.Api.Client.GraphQlApiConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/GraphQlApiConnection.cs:line 107
```

2022-10-14 - could still reproduce issue in current develop branch:
user us2 has roles reviewer, fw-admin, planner
```
2022-10-14T17:38:15.054570+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-14T17:38:15+02:00 Audit - AuthenticateUser (AuthStateProvider.cs in line 69), user us2 successfully authenticated
2022-10-14T17:38:15.122710+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-14T17:38:15+02:00 Error - API Connection (GraphQlApiConnection.cs in line 103), Error while sending query to GraphQL API. Caught by GraphQL client library.
2022-10-14T17:38:15.122845+02:00 fwo-ubu22-desktop fworch-ui:  Message: Your requested role is not in allowed roles
2022-10-14T17:38:15.135372+02:00 fwo-ubu22-desktop fworch-ui:  2022-10-14T17:38:15+02:00 Error - API Connection (GraphQlApiConnection.cs in line 138), Error while sending query to GraphQL API. Query: query getUserByDn($dn: String!) {
2022-10-14T17:38:15.135703+02:00 fwo-ubu22-desktop fworch-ui:    uiuser(where: {uuid: {_eq:  $dn } }) {
2022-10-14T17:38:15.135825+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_id
2022-10-14T17:38:15.135887+02:00 fwo-ubu22-desktop fworch-ui:      uuid
2022-10-14T17:38:15.135941+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_username
2022-10-14T17:38:15.135989+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_language
2022-10-14T17:38:15.136029+02:00 fwo-ubu22-desktop fworch-ui:      uiuser_password_must_be_changed
2022-10-14T17:38:15.136088+02:00 fwo-ubu22-desktop fworch-ui:    }
2022-10-14T17:38:15.136137+02:00 fwo-ubu22-desktop fworch-ui:  }
2022-10-14T17:38:15.136176+02:00 fwo-ubu22-desktop fworch-ui:  , variables: {"dn":"uid=us2,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal"}
2022-10-14T17:38:15.136204+02:00 fwo-ubu22-desktop fworch-ui:   ---
2022-10-14T17:38:15.136252+02:00 fwo-ubu22-desktop fworch-ui:  Exception thrown:
2022-10-14T17:38:15.136283+02:00 fwo-ubu22-desktop fworch-ui:   Exception
2022-10-14T17:38:15.136310+02:00 fwo-ubu22-desktop fworch-ui:  Message:
2022-10-14T17:38:15.136336+02:00 fwo-ubu22-desktop fworch-ui:   Your requested role is not in allowed roles
2022-10-14T17:38:15.136361+02:00 fwo-ubu22-desktop fworch-ui:   
2022-10-14T17:38:15.136395+02:00 fwo-ubu22-desktop fworch-ui:  Stack Trace:
2022-10-14T17:38:15.136419+02:00 fwo-ubu22-desktop fworch-ui:   at FWO.Api.Client.GraphQlApiConnection.SendQueryAsync[QueryResponseType](String query, Object variables, String operationName) in /usr/local/fworch/lib/files/FWO.Api.Client/GraphQlApiConnection.cs:line 107

```

**Comment by tpurschke** [comment]
One issued closed, the rest was not repeoducible

**Comment by tpurschke** [comment]
just experienced "logout/login sometimes fails on first try" with version 6.0

**Comment by tpurschke** [comment]
not reproducible lately
