### ISSUE TITLE
ui recert error during recertification

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1997]
6.1.4 latest develop version 

```
023-02-27T07:34:26+01:00 Error - Load Global Config Items (Config.cs in line 94), Config item with key "emailUser" could not be found. Using default value.
2023-02-27T07:34:26.357281+01:00 debian11 fworch-ui:  2023-02-27T07:34:26+01:00 Error - Load Global Config Items (Config.cs in line 94), Config item with key "emailPassword" could not be found. Using default value.
2023-02-27T07:34:26.357301+01:00 debian11 fworch-ui:  2023-02-27T07:34:26+01:00 Error - Load Global Config Items (Config.cs in line 94), Config item with key "emailSenderAddress" could not be found. Using default value.
2023-02-27T13:40:09.077088+01:00 debian11 fworch-ui:  2023-02-27T13:40:09+01:00 Audit - AuthenticateUser (AuthStateProvider.cs in line 80), user admin successfully authenticated
2023-02-27T13:40:32.947241+01:00 debian11 fworch-ui:  2023-02-27T13:40:32+01:00 Error - Execute Selected Actions (MainLayout.razor in line 264), Unspecified error occured:
2023-02-27T13:40:32.947386+01:00 debian11 fworch-ui:   ---
2023-02-27T13:40:32.947447+01:00 debian11 fworch-ui:  Exception thrown:
2023-02-27T13:40:32.947496+01:00 debian11 fworch-ui:   KeyNotFoundException
2023-02-27T13:40:32.947564+01:00 debian11 fworch-ui:  Message:
2023-02-27T13:40:32.947602+01:00 debian11 fworch-ui:   The given key '1' was not present in the dictionary.
2023-02-27T13:40:32.947642+01:00 debian11 fworch-ui:  Stack Trace:
2023-02-27T13:40:32.947685+01:00 debian11 fworch-ui:   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2023-02-27T13:40:32.947731+01:00 debian11 fworch-ui:     at FWO.Ui.Pages.Certification.InitRecert(Rule rule) in /usr/local/fworch/ui/files/FWO.UI/Pages/Certification.razor:line 608
2023-02-27T13:40:32.947777+01:00 debian11 fworch-ui:     at FWO.Ui.Pages.Certification.Recertify(Rule rule) in /usr/local/fworch/ui/files/FWO.UI/Pages/Certification.razor:line 601
2023-02-27T13:40:32.947820+01:00 debian11 fworch-ui:     at FWO.Ui.Pages.Certification.DoRecerts() in /usr/local/fworch/ui/files/FWO.UI/Pages/Certification.razor:line 552
2023-02-27T13:40:32.947862+01:00 debian11 fworch-ui:     at FWO.Ui.Pages.Certification.ExecuteSelected() in /usr/local/fworch/ui/files/FWO.UI/Pages/Certification.razor:line 500
2023-02-27T13:40:32.949393+01:00 debian11 fworch-ui:  FWORCHAlert - source: "ui", userId: "4", title: "Execute Selected Actions", description: "Unclassified error: : The given key '1' was not present in the dictionary. . See log for details!", alertCode: "UiError"
```

**Comment by tpurschke** [comment]
Tested on fresh installation with demo data (6.1.4).
Can reproduce it everytime I select more than 1 rule for re/de-certification I get the error.
Only recertifying a single rule works.

**Comment by abarz722** [comment]
looks like no proper userDn or groupDn is stored for the owner. The sample-data is still filled with dummy text :-( 
Selecting a real user or a real owner-group (after creating it in the group settings) should fix the problem.
Nevertheless we should enhance the sample data (and maybe the check for Dn/groupDn in the owner data: currently it is only checked if anything is filled in at least one of the fields, not if this represents a valid Dn)

**Comment by tpurschke** [comment]
solved
