### ISSUE TITLE
MW uncaught LDAP exception

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2087]
the following error shows in one of two systems running against openldap servers.
probably occurs when an openldap server is down for maintenance.
```
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]:  ---
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]: Exception thrown:
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]:  LdapException
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]: Message:
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]:  No Such Object
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]: Stack Trace:
2023-06-06T11:31:12.240+02:00 orcprocust1201 fworch.middleware-server[2899935]:  at Novell.Directory.Ldap.LdapResponse.ChkResultCode()
2023-06-06T11:31:12.241+02:00 orcprocust1201 fworch.middleware-server[2899935]:    at Novell.Directory.Ldap.LdapSearchResults.Next()
2023-06-06T11:31:12.241+02:00 orcprocust1201 fworch.middleware-server[2899935]:    at Novell.Directory.Ldap.LdapConnection.Read(String dn, String[] attrs, LdapSearchConstraints cons)
2023-06-06T11:31:12.241+02:00 orcprocust1201 fworch.middleware-server[2899935]:    at FWO.Middleware.Server.Ldap.GetLdapEntry(UiUser user, Boolean validateCredentials) in /usr/local/fworch/middleware/files/FWO.Middleware.Server/Ldap.cs:line 130
2023-06-06T11:31:12.241+02:00 orcprocust1201 fworch.middleware-server[2899935]: 2023-06-06T11:31:12+02:00 Error - Non-LDAP exception cust1ldapp112.admnet.cust1:5636 (Ldap.cs in line 189), Unexpected error while trying to validate user
```

**Comment by tpurschke** [comment]
not merged into upstream branch
