### ISSUE TITLE
Hasura API - container crashes

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2183]
unclear under which circumstances this happens.
there is no report scheduled for 22:15 on fwodemo
happened on all devsrv systems as well as fwodemo all running 6.4.10 or 6.4.11 with hasura v2.28.0

instable hasura version? first test is moving to v2.29.0

might this be connected to OS upgrades?

```
2023-07-09T22:15:15.799996+02:00 fwodemo fworch.middleware-server:   ---
2023-07-09T22:15:15.800012+02:00 fwodemo fworch.middleware-server:  Exception thrown:
2023-07-09T22:15:15.800045+02:00 fwodemo fworch.middleware-server:   Exception
2023-07-09T22:15:15.800061+02:00 fwodemo fworch.middleware-server:  Message:
2023-07-09T22:15:15.800075+02:00 fwodemo fworch.middleware-server:   Error while trying to reach LDAP server ad-test-server:389
2023-07-09T22:15:15.800121+02:00 fwodemo fworch.middleware-server:  Stack Trace:
2023-07-09T22:15:15.800140+02:00 fwodemo fworch.middleware-server:   at FWO.Middleware.Server.Ldap.Connect() in /usr/local/fworch/middleware/files/FWO.Middleware.Server/Ldap.cs:line 51
2023-07-09T22:15:15.800156+02:00 fwodemo fworch.middleware-server:     at FWO.Middleware.Server.Ldap.GetLdapEntry(UiUser user, Boolean validateCredentials) in /usr/local/fworch/middleware/files/FWO.Middleware.Server/Ldap.cs:line 130
2023-07-09T22:15:45.005889+02:00 fwodemo fworch.middleware-server:  2023-07-09T22:15:44+02:00 Error - Report scheduler (ReportScheduler.cs in line 72), Api subscription lead to exception. Retry subscription.
2023-07-09T22:15:45.005953+02:00 fwodemo fworch.middleware-server:   ---
2023-07-09T22:15:45.006014+02:00 fwodemo fworch.middleware-server:  Exception thrown:
2023-07-09T22:15:45.006034+02:00 fwodemo fworch.middleware-server:   WebSocketException
2023-07-09T22:15:45.006050+02:00 fwodemo fworch.middleware-server:  Message:
2023-07-09T22:15:45.006070+02:00 fwodemo fworch.middleware-server:   The remote party closed the WebSocket connection without completing the close handshake.
2023-07-09T22:15:45.006088+02:00 fwodemo fworch.middleware-server:  Stack Trace:
2023-07-09T22:15:45.006105+02:00 fwodemo fworch.middleware-server:   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
2023-07-09T22:15:45.006123+02:00 fwodemo fworch.middleware-server:     at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
2023-07-09T22:15:45.006139+02:00 fwodemo fworch.middleware-server:     at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2023-07-09T22:15:45.006154+02:00 fwodemo fworch.middleware-server:     at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
2023-07-09T22:15:47.208252+02:00 fwodemo fworch.middleware-server:  2023-07-09T22:15:47+02:00 Error - Report scheduler (ReportScheduler.cs in line 72), Api subscription lead to exception. Retry subscription.
2023-07-09T22:15:47.208326+02:00 fwodemo fworch.middleware-server:   ---
2023-07-09T22:15:47.208348+02:00 fwodemo fworch.middleware-server:  Exception thrown:
2023-07-09T22:15:47.208364+02:00 fwodemo fworch.middleware-server:   WebSocketException
2023-07-09T22:15:47.208381+02:00 fwodemo fworch.middleware-server:  Message:
2023-07-09T22:15:47.208440+02:00 fwodemo fworch.middleware-server:   The server returned status code '503' when status code '101' was expected.
2023-07-09T22:15:47.208468+02:00 fwodemo fworch.middleware-server:  Stack Trace:
2023-07-09T22:15:47.208485+02:00 fwodemo fworch.middleware-server:   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
2023-07-09T22:15:47.208502+02:00 fwodemo fworch.middleware-server:     at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
2023-07-09T22:15:47.208557+02:00 fwodemo fworch.middleware-server:     at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ConnectAsync(CancellationToken token) in /_/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs:line 373
2023-07-09T22:15:47.208576+02:00 fwodemo fworch.middleware-server:     at GraphQL.Client.Http.Websocket.GraphQLWSProtocolHandler.<>c__DisplayClass7_0`1.<<CreateSubscriptionObservable>b__0>d.MoveNext() in /_/src/GraphQL.Client/Websocket/GraphQLWSProtocolHandler.cs:line 94
2023-07-09T22:15:50.638546+02:00 fwodemo fworch.middleware-server:  2023-07-09T22:15:50+02:00 Error - Report scheduler (ReportScheduler.cs in line 72), Api subscription lead to exception. Retry subscription.
2023-07-09T22:15:50.638613+02:00 fwodemo fworch.middleware-server:   ---
2023-07-09T22:15:50.638634+02:00 fwodemo fworch.middleware-server:  Exception thrown:
2023-07-09T22:15:50.638650+02:00 fwodemo fworch.middleware-server:   WebSocketException
2023-07-09T22:15:50.638665+02:00 fwodemo fworch.middleware-server:  Message:
                                                                                                      
```

**Comment by tpurschke** [comment]
both devservers running fine so far without OS upgrades
