### ISSUE TITLE
JWT Refresh error request page

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2220]
when clicking on Workflow link while JWT refresh is forced, we get the following error:
```
023-08-14T06:34:26.908Z] Error: System.Collections.Generic.KeyNotFoundException: The given key 'request' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at FWO.Ui.Shared.RequestLayout.<BuildRenderTree>b__0_1(RenderTreeBuilder __builder2) in /home/ize0229/firewall-orchestrator-cactus/roles/ui/files/FWO.UI/Shared/RequestLayout.razor:line 28

   at FWO.Ui.Shared.Sidebar.BuildRenderTree(RenderTreeBuilder __builder)

   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

l
```

**Comment by tpurschke** [comment]
fixed
