### ISSUE TITLE
Reporting - PDF Generation not working on Ubuntu 20.04, 24.04, debian 11

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2385]
Fixes needed for

- [x] ubuntu 24.04
- [x] ubuntu 20.04 (focal) --> no package available, using jammy fails with dependency error (libssl3)
- [x] debian 11
- [x] debian 13 (trixie)?

See also #2322 
Installing the OS package additionally does not help

    sudo apt install wkhtmltopdf

and leads to the same error:

```
    2024-04-26T20:24:47+02:00 Info - Test Log (HtmlToPdfTest.cs in line 29), starting PDF generation
  
      Failed GeneratePdf [36 ms]
      Error Message:
       System.AggregateException : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)
      ----> System.NotSupportedException : Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.
      Stack Trace:
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at WkHtmlToPdfDotNet.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
       at WkHtmlToPdfDotNet.SynchronizedConverter.Convert(IDocument document)
       at FWO.Test.HtmlToPdfTest.GeneratePdf() in /usr/local/fworch/test/csharp/FWO.Test/HtmlToPdfTest.cs:line 55
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
       at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
    --NotSupportedException

```

**Comment by SolidProgramming** [comment]
#2322

**Comment by tpurschke** [comment]
same issue now (since 2024-11-11) also occurs for debian 11

**Comment by tpurschke** [comment]
Customer Report indicates that Ubuntu 20.04 might now also be affected. To be tested.
