### ISSUE TITLE
Subscription error in UI server (seen on one test machine)

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2515]
Server stops logging after the following exception. Restarting the API re-enables logging.
Not tested yet: does the UI still work and does a restart of the UI also fix the logging issue. Assuming both are true.

```
Aug 19 19:51:32 debian12 fworch-ui[989]: 2024-08-19T19:51:32+02:00 Debug - Config subscription update (Config.c>
Aug 19 20:01:43 debian12 fworch-ui[989]: 2024-08-19T20:01:43+02:00 Error - Config Subscription (Config.cs in li>
Aug 19 20:01:43 debian12 fworch-ui[989]:  ---
Aug 19 20:01:43 debian12 fworch-ui[989]: Exception thrown:
Aug 19 20:01:43 debian12 fworch-ui[989]:  Exception
Aug 19 20:01:43 debian12 fworch-ui[989]: Message:
Aug 19 20:01:43 debian12 fworch-ui[989]:  Connection closed by the server.
Aug 19 20:01:43 debian12 fworch-ui[989]: Stack Trace:
Aug 19 20:01:43 debian12 fworch-ui[989]:  at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ReceiveWebsocke>
Aug 19 20:01:45 debian12 fworch-ui[989]: 2024-08-19T20:01:45+02:00 Debug - Config subscription update (Config.c>

```

Also on prod machine

```
2024-09-03T18:29:59.409657+02:00 prodsrv01 fworch-ui:  2024-09-03T18:29:59+02:00 Audit - Session of "xxx" closed (CircuitHandlerService.cs in line 20), Session of user "xxx" (last logged in) with DN: "CN=xx,OU=Benutzer,DC=xxx,DC=DE" was closed.
2024-09-03T22:38:16.004794+02:00 prodsrv01 fworch-ui:  2024-09-03T22:38:16+02:00 Error - Config Subscription (Config.cs in line 170), Config subscription lead to error.
2024-09-03T22:38:16.004990+02:00 prodsrv01 fworch-ui:   ---
2024-09-03T22:38:16.005082+02:00 prodsrv01 fworch-ui:  Exception thrown:
2024-09-03T22:38:16.005160+02:00 prodsrv01 fworch-ui:   WebSocketException
2024-09-03T22:38:16.005243+02:00 prodsrv01 fworch-ui:  Message:
2024-09-03T22:38:16.005405+02:00 prodsrv01 fworch-ui:   The remote party closed the WebSocket connection without completing the close handshake.
2024-09-03T22:38:16.005501+02:00 prodsrv01 fworch-ui:  Stack Trace:
2024-09-03T22:38:16.005581+02:00 prodsrv01 fworch-ui:   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
2024-09-03T22:38:16.005677+02:00 prodsrv01 fworch-ui:     at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
2024-09-03T22:38:16.005769+02:00 prodsrv01 fworch-ui:     at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-09-03T22:38:16.005856+02:00 prodsrv01 fworch-ui:     at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
2024-09-03T22:38:16.005933+02:00 prodsrv01 fworch-ui:     at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T22:38:16.006008+02:00 prodsrv01 fworch-ui:     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2024-09-03T22:38:16.006082+02:00 prodsrv01 fworch-ui:  --- End of stack trace from previous location ---
2024-09-03T22:38:16.006160+02:00 prodsrv01 fworch-ui:     at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ReceiveWebsocketMessagesAsync() in /_/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs:line 513
2024-09-03T22:38:16.006286+02:00 prodsrv01 fworch-ui:  2024-09-03T22:38:16+02:00 Error - Alarm Handling (MainLayout.razor in line 346), Api subscription lead to exception. Retry subscription.
2024-09-03T22:38:16.006365+02:00 prodsrv01 fworch-ui:   ---
2024-09-03T22:38:16.006431+02:00 prodsrv01 fworch-ui:  Exception thrown:
2024-09-03T22:38:16.006495+02:00 prodsrv01 fworch-ui:   WebSocketException
2024-09-03T22:38:16.006559+02:00 prodsrv01 fworch-ui:  Message:
2024-09-03T22:38:16.006626+02:00 prodsrv01 fworch-ui:   The remote party closed the WebSocket connection without completing the close handshake.
2024-09-03T22:38:16.006691+02:00 prodsrv01 fworch-ui:  Stack Trace:
2024-09-03T22:38:16.006799+02:00 prodsrv01 fworch-ui:   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
2024-09-03T22:38:16.006880+02:00 prodsrv01 fworch-ui:     at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
2024-09-03T22:38:16.006948+02:00 prodsrv01 fworch-ui:     at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-09-03T22:38:16.007015+02:00 prodsrv01 fworch-ui:     at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
2024-09-03T22:38:16.007081+02:00 prodsrv01 fworch-ui:     at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T22:38:16.007150+02:00 prodsrv01 fworch-ui:     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2024-09-03T22:38:16.007219+02:00 prodsrv01 fworch-ui:  --- End of stack trace from previous location ---
2024-09-03T22:38:16.007284+02:00 prodsrv01 fworch-ui:     at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.ReceiveWebsocketMessagesAsync() in /_/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs:line 513
2024-09-04T07:27:09.720578+02:00 prodsrv01 fworch-ui:  2024-09-04T07:27:09+02:00 Audit - AuthenticateUser (AuthStateProvider.cs in line 38), user usr32945 successfully authenticated
2024-09-04T07:37:12.945461+02:00 prodsrv01 fworch-ui:  2024-09-04T07:37:12+02:00 Audit - Session of "usr3294
```

**Comment by tpurschke** [comment]
@NilsPur any idea here?
