### ISSUE TITLE
UI Reporting RSB - UI crashes on stest machine v8.4.1

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2589]
- when opening bigger management RSB All - network objects tab on one customer stest machine, the UI crashes without any specific error message.
- the prod system (v8.4 prod) of the same customer (completely different data) is working fine
- might be related to ipv6 ip addresses?! - not really - tests with short (report tab) object lists containing v6 addresses are working; also all tested service object lists are OK.
- should first try to reproduce this on current develop branch with big management 
```
[2024-10-13T08:01:51.120Z] Information: Normalizing '_blazor' to 'https://fwo-stest.ruv.de/_blazor'.
blazor.server.js:1 [2024-10-13T08:01:51.173Z] Information: WebSocket connected to wss://fwo-stest.ruv.de/_blazor?id=CNGXi8FjwkVmbyNYrTKZIQ.
blazor.server.js:1 [2024-10-13T09:29:00.478Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'.
log @ blazor.server.js:1
blazor.server.js:1 [2024-10-13T09:29:00.479Z] Information: Connection disconnected.
5blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
at pn.send (blazor.server.js:1:83536)
at Xt._sendMessage (blazor.server.js:1:56967)
at Xt._sendWithProtocol (blazor.server.js:1:57057)
at Xt.send (blazor.server.js:1:57165)
at Ir.beginInvokeDotNetFromJS (blazor.server.js:1:138660)
at y.invokeDotNetMethodAsync (blazor.server.js:1:4322)
at S.invokeMethodAsync (blazor.server.js:1:5830)
at window.js:10:71
```

**Comment by SolidProgramming** [comment]
1. Where do i get test data for this?
2. What does RSB mean? - I don't know this abbrevation yet
@tpurschke

**Comment by tpurschke** [comment]
> 1. Where do i get test data for this?

you may start with a 500 rules rulebase as referenced on our private repo: https://github.com/CactuseSecurity/FWO_private/blob/fba4f11f2b4401f075b69cdea73fd2d2cabad756/dev-infos/sample-data/cp500rules.md

> 2. What does RSB mean? - I don't know this abbrevation yet

simply Right Side Bar :-) - sorry for the confusion

**Comment by SolidProgramming** [comment]
I dug a bit and this maybe  could have to do with the new UI message "system" but not sure. If there are Ui messages while other UI stuff happens the message list could cause issues and if the task for the messages/loading of the data crash the stack trace maybe can't follow where the error happened. will further investigate this tomorrow.

**Comment by SolidProgramming** [comment]
@tpurschke imported the 500 rules and this branch https://github.com/SolidProgramming/firewall-orchestrator/tree/2589-ui-reporing-rsb-ui-crashes-on-stest-machine-v841 doesn't break

**Comment by tpurschke** [comment]
@SolidProgramming can you please have a look at this?

```
blazor.server.js:1 
 [2024-10-26T10:37:58.948Z] Error: System.InvalidOperationException: More than one sibling of element 'tr' has the same key value, 'FWO.Api.Data.NetworkObject'. Key values must be unique.
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ThrowExceptionForDuplicateKey(Object key, RenderTreeFrame& frame)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.BuildKeyToInfoLookup(DiffContext diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
log	@	blazor.server.js:1
```

**Comment by tpurschke** [comment]
@Y4nnikH normalized test data which reproduces the issue can be found here: https://xfer.cactus.de/index.php/f/695816.
pls. contact me if you have issues importing it.

**Comment by tpurschke** [comment]
two attempts to reproduce failed
