### ISSUE TITLE
UI Re-Assign interface request - UI crashes on stest machine

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2603]
```
2024-10-18T12:23:40.024690+02:00 lxm02199 fworch-ui:  2024-10-18T12:23:40+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role implementer: query getRuleActions {  stm_action {    action_id    action_name ...
2024-10-18T12:23:40.027493+02:00 lxm02199 fworch-ui:  2024-10-18T12:23:40+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role implementer: query getTracking {  stm_track {    track_id    track_name  }}...
2024-10-18T12:23:40.029594+02:00 lxm02199 fworch-ui:  2024-10-18T12:23:40+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role implementer: query getIpProtocols {  stm_ip_proto {    ip_proto_id    ip_proto_...
2024-10-18T12:24:40.810326+02:00 lxm02199 fworch-ui:  Process terminated. Assertion failed.
2024-10-18T12:24:40.810388+02:00 lxm02199 fworch-ui:  The assigned value is null but the Nullable option is not enabled.
2024-10-18T12:24:40.810421+02:00 lxm02199 fworch-ui:     at FWO.Ui.Shared.Dropdown`1.set_SelectedElement(ElementType value) in /usr/local/fworch/ui/files/FWO.UI/Shared/Dropdown.razor:line 151
2024-10-18T12:24:40.810450+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
2024-10-18T12:24:40.810477+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
2024-10-18T12:24:40.810515+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
2024-10-18T12:24:40.810542+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
2024-10-18T12:24:40.810572+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
2024-10-18T12:24:40.810600+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
2024-10-18T12:24:40.810630+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-10-18T12:24:40.810666+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
2024-10-18T12:24:40.810693+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-10-18T12:24:40.810720+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
2024-10-18T12:24:40.810881+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
2024-10-18T12:24:40.810950+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
2024-10-18T12:24:40.810989+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
2024-10-18T12:24:40.811023+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
2024-10-18T12:24:40.811053+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
2024-10-18T12:24:40.811086+02:00 lxm02199 fworch-ui:     at InvokeStub_WebRendererInteropMethods.DispatchEventAsync(Object, Span`1)
2024-10-18T12:24:40.811123+02:00 lxm02199 fworch-ui:     at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-10-18T12:24:40.811229+02:00 lxm02199 fworch-ui:     at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
2024-10-18T12:24:40.811258+02:00 lxm02199 fworch-ui:     at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
2024-10-18T12:24:40.811283+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass45_0.<BeginInvokeDotNetFromJS>b__1()
2024-10-18T12:24:40.811312+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<InvokeAsync>g__Execute|8_0(ValueTuple`3 state)
2024-10-18T12:24:40.811358+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.InvokeAsync(Action action)
2024-10-18T12:24:40.811386+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.BeginInvokeDotNetFromJS(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
2024-10-18T12:24:40.811420+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811460+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Server.ComponentHub.BeginInvokeDotNetFromJS(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
2024-10-18T12:24:40.811489+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811517+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.Components.Server.ComponentHub.BeginInvokeDotNetFromJS(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
2024-10-18T12:24:40.811555+02:00 lxm02199 fworch-ui:     at lambda_method52(Closure, Object, Object[])
2024-10-18T12:24:40.811583+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
2024-10-18T12:24:40.811607+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811633+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, HubConnectionContext connection, IServiceProvider serviceProvider)
2024-10-18T12:24:40.811666+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
2024-10-18T12:24:40.811698+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811728+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
2024-10-18T12:24:40.811764+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamResponse, Boolean isStreamCall)
2024-10-18T12:24:40.811794+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811821+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamResponse, Boolean isStreamCall)
2024-10-18T12:24:40.811846+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.ChannelBasedSemaphore.RunTask[TState](Func`2 callback, TState state)
2024-10-18T12:24:40.811872+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-10-18T12:24:40.811897+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.ChannelBasedSemaphore.RunTask[TState](Func`2 callback, TState state)
2024-10-18T12:24:40.811923+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.ChannelBasedSemaphore.RunAsync[TState](Func`2 callback, TState state)
2024-10-18T12:24:40.811953+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ProcessInvocation(HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamResponse)
2024-10-18T12:24:40.811982+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DispatchMessageAsync(HubConnectionContext connection, HubMessage hubMessage)
2024-10-18T12:24:40.812010+02:00 lxm02199 fworch-ui:     at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
2024-10-18T12:24:40.812035+02:00 lxm02199 fworch-ui:     at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2024-10-18T12:24:40.812065+02:00 lxm02199 fworch-ui:     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2024-10-18T12:24:40.812090+02:00 lxm02199 fworch-ui:     at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-10-18T12:24:40.812116+02:00 lxm02199 fworch-ui:     at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```

**Comment by tpurschke** [comment]
**Global Error Handling** in your UI framework, which ensures that unexpected exceptions are caught and handled gracefully, without crashing the entire application. Depending on the framework you're using, the implementation details can vary. In your case, since the context seems to be Blazor (a .NET web framework), Blazor provides specific ways to handle errors at a global level using `ErrorBoundary` components.

### Blazor's `ErrorBoundary` for Global Error Handling

The `ErrorBoundary` component in Blazor allows you to catch and manage unhandled exceptions within the UI. Instead of allowing an error to crash the whole application or leave the UI in an inconsistent state, you can present a user-friendly message, log the error, or attempt a recovery strategy. This feature improves the robustness of your application, ensuring users don’t face a broken or unresponsive interface when something goes wrong.

Here’s a more detailed breakdown of how it works and how you can implement it in Blazor:

#### 1. **Basic ErrorBoundary Usage**
An `ErrorBoundary` wraps around your components and catches any unhandled exceptions that occur within them. When an error occurs, Blazor will display the fallback content you provide.

**Example:**

```razor
<ErrorBoundary>
    <ChildContent>
        <!-- Your component(s) here -->
        <Dropdown SelectedElement="..."/>
    </ChildContent>
    <ErrorContent>
        <p>An error occurred while loading the dropdown. Please try again later.</p>
    </ErrorContent>
</ErrorBoundary>
```

- **`ChildContent`**: This contains the components that are being monitored for exceptions.
- **`ErrorContent`**: This is the fallback content that will be displayed if an error occurs.

#### 2. **Catching and Displaying Errors**
When an exception is thrown inside any of the components wrapped in the `ErrorBoundary`, the `ErrorContent` will be displayed instead of the component’s original content. This gives you a controlled way to communicate to the user that something went wrong.

**Example UI Handling for `Dropdown`:**

```razor
<ErrorBoundary>
    <ChildContent>
        <Dropdown SelectedElement="selectedElement" />
    </ChildContent>
    <ErrorContent>
        <p>Oops! Something went wrong while loading the dropdown. Please refresh the page.</p>
    </ErrorContent>
</ErrorBoundary>
```

This setup prevents the dropdown component from crashing the entire UI, and instead shows the user-friendly message.

#### 3. **Logging Errors Globally**
While displaying error messages to users is important, it's often essential to **log errors** for debugging and troubleshooting purposes. You can handle error logging inside the `OnError` event of the `ErrorBoundary`.

Here's how you might capture and log the error:

**Custom ErrorBoundary with Logging:**

```razor
@inherits ErrorBoundary
@inject ILogger<CustomErrorBoundary> Logger

<ChildContent>
    @ChildContent
</ChildContent>

<ErrorContent>
    <p>Something went wrong! Our team has been notified.</p>
</ErrorContent>

@code {
    protected override void OnError(Exception exception)
    {
        // Log the error or send it to an external service
        Logger.LogError(exception, "An unhandled exception occurred in the UI.");

        // Optionally reset the error boundary
        // Recover();
    }
}
```

In this example:
- You inject an `ILogger` instance and use it to log the exception details.
- You override the `OnError` method, which gets called whenever an unhandled exception occurs within the `ErrorBoundary`.

#### 4. **Error Boundary Reuse (Centralized Error Handling)**
You can create a reusable `ErrorBoundary` component that wraps around other UI components in your app. This centralizes error handling across your application, reducing boilerplate code and ensuring consistent error messages.

**Reusable ErrorBoundary Component (CustomErrorBoundary.razor):**

```razor
@inherits ErrorBoundary

<ChildContent>
    @ChildContent
</ChildContent>

<ErrorContent>
    <p>An unexpected error occurred. Please contact support.</p>
</ErrorContent>

@code {
    protected override void OnError(Exception exception)
    {
        // Log the error, notify an admin, etc.
        // For example, sending logs to an external service
    }
}
```

Then, you can wrap any component or page with this reusable `ErrorBoundary`:

```razor
<CustomErrorBoundary>
    <YourComponent />
</CustomErrorBoundary>
```

#### 5. **ErrorBoundary in Layouts**
You can also place the `ErrorBoundary` in layout files to catch errors across larger portions of your application, such as entire sections or pages.

**Example (MainLayout.razor):**

```razor
<ErrorBoundary>
    <ChildContent>
        @Body
    </ChildContent>
    <ErrorContent>
        <p>An error occurred in the layout. Please refresh the page or contact support.</p>
    </ErrorContent>
</ErrorBoundary>
```

In this example, if any error happens while rendering a page inside the layout, the fallback content will be displayed, and the entire layout won’t crash.

#### 6. **Handling Cascading Errors**
If your application has cascading errors that need to bubble up to a higher-level error handler, you can nest `ErrorBoundary` components at different levels to ensure you handle errors at the appropriate scope.

### Benefits of Global Error Handling
1. **User Experience**: Prevents your users from seeing broken UI or encountering application crashes.
2. **Debugging and Logging**: Logs errors for later analysis, making it easier to troubleshoot.
3. **Granularity**: You can wrap individual components, pages, or entire layouts to handle errors at the appropriate level.
4. **Consistency**: Ensures a uniform error-handling approach across your app.
5. **Recovery**: Provides a way to recover from errors (e.g., allow the user to retry an operation or refresh the page).

By using `ErrorBoundary` in Blazor, you can significantly enhance the reliability and user experience of your UI, preventing unexpected crashes and ensuring that your application continues to function even when individual components fail.
