### ISSUE TITLE
UI browser protected storage contains wrong key after fworch upgrade

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#604]
try to catch the following error
```
Dec 20 17:21:01 devsrvffm fworch-ui[17783]: #033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:       Unhandled exception rendering component: The key {524bd3a7-d5ff-4202-ae99-6379477f3b19} was not found in the key ring.
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:       System.Security.Cryptography.CryptographicException: The key {524bd3a7-d5ff-4202-ae99-6379477f3b19} was not found in the key ring.
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at FWO.Ui.Pages.Login.OnAfterRenderAsync(Boolean firstRender) in /usr/local/fworch/ui/files/FWO_UI/Pages/Login.razor:line 71
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:       Unhandled exception in circuit 'clGG2Wby0gHvf4TdIikZE65OJCt-H3uKelSiy5HtVWY'.
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:       System.Security.Cryptography.CryptographicException: The key {524bd3a7-d5ff-4202-ae99-6379477f3b19} was not found in the key ring.
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at FWO.Ui.Pages.Login.OnAfterRenderAsync(Boolean firstRender) in /usr/local/fworch/ui/files/FWO_UI/Pages/Login.razor:line 71
Dec 20 17:21:01 devsrvffm fworch-ui[17783]:          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by tpurschke** [comment]
wont fix
